-- FUNCTION: public.periodstat(timestamp with time zone, timestamp with time zone)

-- DROP FUNCTION IF EXISTS public.periodstat(timestamp with time zone, timestamp with time zone);

CREATE OR REPLACE FUNCTION public.periodstat(
	start_ts timestamp with time zone,
	end_ts timestamp with time zone DEFAULT now())
    RETURNS TABLE(x_ainsidepower numeric, x_aoutsidecurrent numeric, x_aoutsidepower numeric, a_aoutsidepower numeric, x_apower numeric, a_apower numeric, d_batchargetoday numeric, d_batchargetotal numeric, n_batchargetotal numeric, a_batchargetotal numeric, n_batdischargetoday numeric, a_batdischargetoday numeric, x_batdischargetotal numeric, d_batdischargetoday numeric, d_batdischargetotal numeric, x_batterycurrent numeric, x_batteryenergy numeric, n_batteryenergy numeric, a_batteryenergy numeric, x_batterypower numeric, a_batterypower numeric, x_batterytemp numeric, n_batterytemp numeric, a_batterytemp numeric, x_batteryvolt numeric, n_batteryvolt numeric, a_batteryvolt numeric, x_binsidepower numeric, x_boutsidecurrent numeric, x_boutsidepower numeric, a_boutsidepower numeric, x_bpower numeric, a_bpower numeric, x_cinsidepower numeric, a_cinsidepower numeric, x_coutsidecurrent numeric, x_coutsidepower numeric, a_coutsidepower numeric, x_cpower numeric, a_cpower numeric, x_dailyused numeric, a_dailyused numeric, x_dctemp numeric, a_dctemp numeric, n_dctemp numeric, x_genapower numeric, a_genapower numeric, n_genavolt numeric, x_genavolt numeric, a_genbpower numeric, n_genbvolt numeric, x_genbvolt numeric, a_genbvolt numeric, x_gencpower numeric, a_gencpower numeric, n_gencvolt numeric, x_gencvolt numeric, a_gencvolt numeric, a_gendailytime numeric, x_gentoday numeric, a_gentoday numeric, d_gentotal numeric, x_gentotal numeric, a_gentotal numeric, x_gentotalpower numeric, a_gentotalpower numeric, d_gridbuytoday numeric, n_gridbuytoday numeric, a_gridbuytoday numeric, x_gridbuytoday numeric, d_gridbuytotal numeric, a_gridfac numeric, n_gridfac numeric, x_gridfac numeric, x_gridinsidetotalpac numeric, a_gridinsidetotalpac numeric, x_gridinsidetotalsac numeric, a_gridinsidetotalsac numeric, x_gridoutsidetotalpac numeric, a_gridoutsidetotalpac numeric, x_gridoutsidetotalsac numeric, a_gridoutsidetotalsac numeric, d_gridselltoday numeric, n_gridselltoday numeric, a_gridselltoday numeric, x_gridselltoday numeric, d_gridselltotal numeric, x_gridvac1 numeric, n_gridvac1 numeric, x_gridvac2 numeric, n_gridvac2 numeric, x_gridvac3 numeric, n_gridvac3 numeric, x_heatsinktemp numeric, n_heatsinktemp numeric, a_heatsinktemp numeric, x_iac1 numeric, n_iac1 numeric, a_iac1 numeric, x_iac2 numeric, n_iac2 numeric, a_iac2 numeric, x_iac3 numeric, n_iac3 numeric, a_iac3 numeric, x_invacurrent numeric, n_invacurrent numeric, a_invacurrent numeric, x_invapower numeric, n_invapower numeric, a_invapower numeric, x_invavolt numeric, n_invavolt numeric, x_invbcurrent numeric, n_invbcurrent numeric, a_invbcurrent numeric, x_invbpower numeric, n_invbpower numeric, a_invbpower numeric, x_invbvolt numeric, n_invbvolt numeric, a_invbvolt numeric, x_invccurrent numeric, n_invccurrent numeric, a_invccurrent numeric, x_invcpower numeric, n_invcpower numeric, a_invcpower numeric, x_invcvolt numeric, n_invcvolt numeric, a_invcvolt numeric, x_invfac numeric, n_invfac numeric, a_invfac numeric, x_invtotalpower numeric, n_invtotalpower numeric, a_invtotalpower numeric, x_invtotalsac numeric, n_invtotalsac numeric, a_invtotalsac numeric, x_ipv1 numeric, n_ipv1 numeric, a_ipv1 numeric, x_ipv2 numeric, n_ipv2 numeric, a_ipv2 numeric, x_loadapower numeric, n_loadapower numeric, a_loadapower numeric, x_loadavolt numeric, n_loadavolt numeric, a_loadavolt numeric, x_loadbpower numeric, n_loadbpower numeric, a_loadbpower numeric, x_loadbvolt numeric, n_loadbvolt numeric, a_loadbvolt numeric, x_loadcpower numeric, n_loadcpower numeric, a_loadcpower numeric, x_loadcvolt numeric, n_loadcvolt numeric, a_loadcvolt numeric, x_loadtotalpac numeric, n_loadtotalpac numeric, a_loadtotalpac numeric, x_loadtotalsac numeric, n_loadtotalsac numeric, a_loadtotalsac numeric, x_pf numeric, n_pf numeric, a_pf numeric, x_ppv1 numeric, n_ppv1 numeric, x_ppv2 numeric, n_ppv2 numeric, x_pvetoday numeric, n_pvetoday numeric, d_pvhistory numeric, x_todaypv1 numeric, n_todaypv1 numeric, x_todaypv2 numeric, n_todaypv2 numeric, d_totalused numeric, n_totalused numeric, a_totalused numeric, x_vpv1 numeric, n_vpv1 numeric, a_vpv1 numeric, x_vpv2 numeric, n_vpv2 numeric, a_vpv2 numeric) 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
DECLARE
    voltageThreshold CONSTANT numeric := 100;
    solarPowerThreshold CONSTANT numeric := 0;
    solarVoltageThreshold CONSTANT numeric := 0;
BEGIN
    RETURN QUERY
    SELECT 
	MAX(aInsidePower) as x_aInsidePower,
	MAX(aOutsideCurrent) as x_aOutsideCurrent,
	MAX(aOutsidePower) as x_aOutsidePower,
    AVG(aOutsidePower) as a_aOutsidePower,
	MAX(aPower) as x_aPower,
    AVG(aPower) as a_aPower,
	MAX(batChargeToday) - MIN(batChargeToday) as d_batChargeToday,
	MAX(batChargeTotal) - MIN(batChargeTotal) as d_batChargeTotal,
    MIN(batChargeTotal) as n_batChargeTotal,
    AVG(batChargeTotal) as a_batChargeTotal,
    MIN(batDischargeToday) as n_batDischargeToday,
    AVG(batDischargeToday) as a_batDischargeToday,
    MAX(batDischargeTotal) as x_batDischargeTotal,
	MAX(batDischargeToday) - MIN(batDischargeToday) as d_batDischargeToday,
	MAX(batDischargeTotal) - MIN(batDischargeTotal) as d_batDischargeTotal,
	MAX(batteryCurrent) as x_batteryCurrent,
	MAX(batteryEnergy) as x_batteryEnergy,
    MIN(batteryEnergy) as n_batteryEnergy,
    AVG(batteryEnergy) as a_batteryEnergy,
	MAX(batteryPower) as x_batteryPower,
    AVG(batteryPower) as a_batteryPower,
    MAX(batteryTemp) as x_batteryTemp,
	MIN(batteryTemp) as n_batteryTemp,
	AVG(batteryTemp) as a_batteryTemp,
	MAX(batteryVolt) as x_batteryVolt,
    MIN(batteryVolt) as n_batteryVolt,
    AVG(batteryVolt) as a_batteryVolt,
	MAX(bInsidePower) as x_bInsidePower,
	MAX(bOutsideCurrent) as x_bOutsideCurrent,
	MAX(bOutsidePower) as x_bOutsidePower,
    AVG(bOutsidePower) as a_bOutsidePower,
	MAX(bPower) as x_bPower,
    AVG(bPower) as a_bPower,
	MAX(cInsidePower) as x_cInsidePower,
    AVG(cInsidePower) as a_cInsidePower,
	MAX(cOutsideCurrent) as x_cOutsideCurrent,
	MAX(cOutsidePower) as x_cOutsidePower,
    AVG(cOutsidePower) as a_cOutsidePower,
	MAX(cPower) as x_cPower,
    AVG(cPower) as a_cPower,
	MAX(dailyUsed) as x_dailyUsed,
    AVG(dailyUsed) as a_dailyUsed,
	MAX(dcTemp) as x_dcTemp,
    AVG(dcTemp) as a_dcTemp,
    MIN(dcTemp) as n_dcTemp,
	MAX(genAPower) as x_genAPower,
    AVG(genAPower) as a_genAPower,
    MIN(genAVolt) FILTER(WHERE genAVolt>voltageThreshold) as n_genAVolt,
    MAX(genAVolt) as x_genAVolt,
    AVG(genBPower) as a_genBPower,
    MIN(genBVolt) FILTER(WHERE genBVolt>voltageThreshold) as n_genBVolt,
    MAX(genBVolt) as x_genBVolt,
    AVG(genBVolt) as a_genBVolt,
    MAX(genCPower) as x_genCPower,
    AVG(genCPower) as a_genCPower,
    MIN(genCVolt) FILTER(WHERE genCVolt>voltageThreshold) as n_genCVolt,
    MAX(genCVolt) as x_genCVolt,
    AVG(genCVolt) as a_genCVolt,
    AVG(genDailyTime) as a_genDailyTime,
    MAX(genToday) as x_genToday,
    AVG(genToday) as a_genToday,
    MAX(genTotal) - MIN(genTotal) as d_genTotal,
    MAX(genTotal) as x_genTotal,
    AVG(genTotal) as a_genTotal,
    MAX(genTotalPower) as x_genTotalPower,
    AVG(genTotalPower) as a_genTotalPower,
    MAX(gridBuyToday) - MIN(gridBuyToday) as d_gridBuyToday,
    MIN(gridBuyToday) as n_gridBuyToday,
    AVG(gridBuyToday) as a_gridBuyToday,
    MAX(gridBuyToday) as x_gridBuyToday,
    MAX(gridBuyTotal)  - MIN(gridBuyTotal) as d_gridBuyTotal,
    AVG(gridFac) as a_gridFac,
    MIN(gridFac) as n_gridFac,
    MAX(gridFac) as x_gridFac,
    MAX(gridInsideTotalPac) as x_gridInsideTotalPac,
    AVG(gridInsideTotalPac) as a_gridInsideTotalPac,
    MAX(gridInsideTotalSac) as x_gridInsideTotalSac,
    AVG(gridInsideTotalSac) as a_gridInsideTotalSac,
    MAX(gridOutsideTotalPac) as x_gridOutsideTotalPac,
    AVG(gridOutsideTotalPac) as a_gridOutsideTotalPac,
    MAX(gridOutsideTotalSac) as x_gridOutsideTotalSac,
    AVG(gridOutsideTotalSac) as a_gridOutsideTotalSac,
    MAX(gridSellToday) - MIN(gridSellToday) as d_gridSellToday,
    MIN(gridSellToday) as n_gridSellToday,
    AVG(gridSellToday) as a_gridSellToday,
    MAX(gridSellToday) as x_gridSellToday,
    MAX(gridSellTotal) - MIN(gridSellTotal) as d_gridSellTotal,
    MAX(grid_Vac1) as x_GridVac1,
    MIN(grid_Vac1) FILTER(WHERE grid_Vac1>voltageThreshold) as n_GridVac1,
    MAX(grid_Vac2) as x_GridVac2,
    MIN(grid_Vac2) FILTER(WHERE grid_Vac2>voltageThreshold) as n_GridVac2,
    MAX(grid_Vac3) as x_GridVac3,
    MIN(grid_Vac3) FILTER(WHERE grid_Vac3>voltageThreshold) as n_GridVac3,
    MAX(heatSinkTemp) as x_heatSinkTemp,
    MIN(heatSinkTemp) as n_heatSinkTemp,
    AVG(heatSinkTemp) as a_heatSinkTemp,
    MAX(iac1) as x_iac1,
    MIN(iac1) as n_iac1,
    AVG(iac1) as a_iac1,
    MAX(iac2) as x_iac2,
    MIN(iac2) as n_iac2,
    AVG(iac2) as a_iac2,
    MAX(iac3) as x_iac3,
    MIN(iac3) as n_iac3,
    AVG(iac3) as a_iac3,
    MAX(invACurrent) as x_invACurrent,
    MIN(invACurrent) as n_invACurrent,
    AVG(invACurrent) as a_invACurrent,
    MAX(invAPower) as x_invAPower,
    MIN(invAPower) as n_invAPower,
    AVG(invAPower) as a_invAPower,
    MAX(invAVolt) as x_invAVolt,
    MIN(invAVolt) FILTER(WHERE invAVolt>voltageThreshold) as n_invAVolt,
    MAX(invBCurrent) as x_invBCurrent,
    MIN(invBCurrent) as n_invBCurrent,
    AVG(invBCurrent) as a_invBCurrent,
    MAX(invBPower) as x_invBPower,
    MIN(invBPower) as n_invBPower,
    AVG(invBPower) as a_invBPower,
    MAX(invBVolt) as x_invBVolt,
    MIN(invBVolt) FILTER(WHERE invBVolt>voltageThreshold) as n_invBVolt,
    AVG(invBVolt) as a_invBVolt,
    MAX(invCCurrent) as x_invCCurrent,
    MIN(invCCurrent) as n_invCCurrent,
    AVG(invCCurrent) as a_invCCurrent,
    MAX(invCPower) as x_invCPower,
    MIN(invCPower) as n_invCPower,
    AVG(invCPower) as a_invCPower,
    MAX(invCVolt) as x_invCVolt,
    MIN(invCVolt) FILTER(WHERE invCVolt>voltageThreshold) as n_invCVolt,
    AVG(invCVolt) as a_invCVolt,
    MAX(invFac) as x_invFac,
    MIN(invFac) as n_invFac,
    AVG(invFac) as a_invFac,
    MAX(invTotalPower) as x_invTotalPower,
    MIN(invTotalPower) as n_invTotalPower,
    AVG(invTotalPower) as a_invTotalPower,
    MAX(invTotalSac) as x_invTotalSac,
    MIN(invTotalSac) as n_invTotalSac,
    AVG(invTotalSac) as a_invTotalSac,
    MAX(ipv1) as x_ipv1,
    MIN(ipv1) as n_ipv1,
    AVG(ipv1) as a_ipv1,
    MAX(ipv2) as x_ipv2,
    MIN(ipv2) as n_ipv2,
    AVG(ipv2) as a_ipv2,
    MAX(loadAPower) as x_loadAPower,
    MIN(loadAPower) as n_loadAPower,
    AVG(loadAPower) as a_loadAPower,
    MAX(loadAVolt) as x_loadAVolt,
    MIN(loadAVolt) FILTER(WHERE loadAVolt>voltageThreshold) as n_loadAVolt,
    AVG(loadAVolt) as a_loadAVolt,
    MAX(loadBPower) as x_loadBPower,
    MIN(loadBPower) as n_loadBPower,
    AVG(loadBPower) as a_loadBPower,
    MAX(loadBVolt) as x_loadBVolt,
    MIN(loadBVolt) FILTER(WHERE loadBVolt>voltageThreshold) as n_loadBVolt,
    AVG(loadBVolt) as a_loadBVolt,
    MAX(loadCPower) as x_loadCPower,
    MIN(loadCPower) as n_loadCPower,
    AVG(loadCPower) as a_loadCPower,
    MAX(loadCVolt) as x_loadCVolt,
    MIN(loadCVolt) FILTER(WHERE loadCVolt>voltageThreshold) as n_loadCVolt,
    AVG(loadCVolt) as a_loadCVolt,
    MAX(loadTotalPac) as x_loadTotalPac,
    MIN(loadTotalPac) as n_loadTotalPac,
    AVG(loadTotalPac) as a_loadTotalPac,
    MAX(loadTotalSac) as x_loadTotalSac,
    MIN(loadTotalSac) as n_loadTotalSac,
    AVG(loadTotalSac) as a_loadTotalSac,
    MAX(pf) as x_pf,
    MIN(pf) as n_pf,
    AVG(pf) as a_pf,
    MAX(ppv1) as x_ppv1,
    MIN(ppv1) FILTER(WHERE ppv1>voltageThreshold) as n_ppv1,
    MAX(ppv2) as x_ppv2,
    MIN(ppv2) FILTER(WHERE ppv2>solarPowerThreshold) as n_ppv2,
    MAX(pvEtoday) as x_pvEtoday,
    MIN(pvEtoday) FILTER(WHERE pvEtoday>solarPowerThreshold) as n_pvEtoday,
    MAX(pvHistory) - MIN(pvHistory) as d_pvHistory,
    MAX(todayPv1) as x_todayPv1,
    MIN(todayPv1) FILTER(WHERE todayPv1>solarPowerThreshold) as n_todayPv1,
    MAX(todayPv2) as x_todayPv2,
    MIN(todayPv2) FILTER(WHERE todayPv2>solarPowerThreshold) as n_todayPv2,
    MAX(totalUsed) - MIN(totalUsed) as d_totalUsed,
    MIN(totalUsed) as n_totalUsed,
    AVG(totalUsed) as a_totalUsed,
    MAX(vpv1) as x_vpv1,
    MIN(vpv1) FILTER(WHERE vpv1>solarVoltageThreshold) as n_vpv1,
    AVG(vpv1) as a_vpv1,
    MAX(vpv2) as x_vpv2,
    MIN(vpv2) FILTER(WHERE vpv2>solarVoltageThreshold) as n_vpv2,
    AVG(vpv2) as a_vpv2
	
    FROM parameterHistory(start_ts, end_ts) h1;
END;
$BODY$;

ALTER FUNCTION public.periodstat(timestamp with time zone, timestamp with time zone)
    OWNER TO sigma;
